# This workflow assigns our default project to new issues
name: Assign new issues to default project's Funnel column
on:
  issues:
    types: [opened]

jobs:
  add-new-issues-to-project-column:
    runs-on: ubuntu-latest
    steps:
      - name: add-new-issues-to-organization-based-project-column
        uses: docker://takanabe/github-actions-automate-projects:v0.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.ORG_GITHUB_TOKEN }}
          GITHUB_PROJECT_URL: https://github.com/orgs/lyne-design-system/projects/4
          GITHUB_PROJECT_COLUMN_NAME: Funnel
