name: Continuous Integration Secure
# Secure execution of continuous integration jobs
# which are performed upon completion of the
# "Continuous Integration" workflow
# https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
on:
  workflow_run:
    workflows: ['Continuous Integration']
    types: [completed]

jobs:
  preview-image:
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.conclusion == 'success' && (
        github.event.workflow_run.event == 'pull_request' || (
          github.event.workflow_run.event == 'push' &&
          github.event.workflow_run.head_branch == 'main'
        )
      )
    env:
      IMAGE_REPO: ghcr.io/${{ github.repository }}/storybook-preview
      IMAGE_TAG: rev-${{ github.event.workflow_run.head_sha }}
    steps:
      - uses: actions/checkout@v3
      - name: Download artifacts
        uses: ./.github/actions/download-artifacts-from-workflow
        with:
          artifacts: 'storybook'
      - run: mkdir storybook-static
      - run: unzip storybook.zip -d storybook-static
      - name: Remove files with forbidden extensions
        run: node ./ci/clean-storybook-files.js

      - name: 'Container: Login to GitHub Container Repository'
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io --username ${{ github.actor }} --password-stdin
      - name: 'Container: Build image'
        run: docker build -t $IMAGE_REPO:$IMAGE_TAG .
      - name: 'Container: Publish image'
        run: docker push $IMAGE_REPO:$IMAGE_TAG

  codecov:
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success'
    steps:
      - uses: actions/checkout@v3
      - name: Download artifacts
        uses: ./.github/actions/download-artifacts-from-workflow
        with:
          artifacts: 'pr, coverage'
      - run: unzip pr.zip
      - run: mkdir coverage
      - run: unzip coverage.zip -d coverage
      - name: Read PR number
        id: pr-number
        run: echo "pr=$(<NR)" >> $GITHUB_OUTPUT
        shell: bash
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: coverage
          override_branch: ${{ github.event.workflow_run.head_branch }}
          override_commit: ${{ github.event.workflow_run.head_commit.id }}
          override_pr: ${{ steps.yarn-cache-dir-path.outputs.pr }}
          fail_ci_if_error: true
          verbose: true
