name: Preview Image Cleanup

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 5 * * *'

permissions:
  packages: write

jobs:
  preview-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/delete-package-versions@v4
        with:
          package-name: 'lyne-components/storybook-preview'
          package-type: 'container'
          ignore-versions: '^preview-'
          min-versions-to-keep: 0
      - uses: actions/delete-package-versions@v4
        with:
          package-name: 'lyne-components/storybook-preview'
          package-type: 'container'
          delete-only-untagged-versions: 'true'
