name: Preview Image Cleanup

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 5 * * *'

permissions:
  packages: write

jobs:
  preview-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const response = github.rest.packages.getAllPackageVersionsForPackageOwnedByUser({
              package_type: 'container',
              package_name: 'lyne-components/storybook-preview',
              username: context.repo.owner,
            });
            const versions = await github.paginate(response);
            console.log(versions)
      - uses: actions/delete-package-versions@v4
        with:
          package-name: 'lyne-components/storybook-preview'
          package-type: 'container'
          delete-only-untagged-versions: 'true'
